# Model Parameters
vocab_len: 30171
ingredient_dim: 3769
verb_dim: 250
word_dim: 256
sentEnd_hiddens: 768
recipe_inDim: 512
recipe_nlayers: 6
recipe_nheads: 8
sentDec_hiddens: 512
sentDec_nlayers: 3
cvae_latent_dim: 1024
cvae_hidden_dim: 512
cvae_n_hidden_layers: 3
cvae_concat_next: True
learnable_prior: False

# Loss parameters
gamma: 1.0
alpha: 3
final_kl_weight: 0.2
kl_annealing_steps: 100000

# optimizer parameters
weight_decay: 0.01
beta_1: 0.9
beta_2: 0.999

# dataset utils
vocab_bin: 'dataset/vocab/vocab_bin_30171.pkl'
vocab_ing: 'dataset/vocab/vocab_ing_3769.pkl'
vocab_verb: 'dataset/vocab/vocab_verbs_250.pkl'

# dataset
# path for Recipe1M json file
dataset_json: #path to Recipe1M json file
# path for YCII json test splits
json_splits: 'dataset/ycii_videos_splits.json'
# path for a pickle file with univl embeddings
univl_features_file: '/user/m.abdelsalam/datasets/Recipe1M/train_val_univl_embeddings.pickle'
# path for a pickle file with the mean and standard deviation of the univl embeddings to normalize
univl_features_mean_std_file: '/user/m.abdelsalam/datasets/Recipe1M/univl_embeddings_mean_std.pickle'